n1=input ('Escreva algo:')
print ('O tipo primitivo é', type(n1))
print ('Ele só tem espaços?',n1.isspace())
print ('Ele é alfabético?', n1.isalpha())
print ('Ele é numérico?', n1.isnumeric())
print ('Ele é alfanumérico?', n1.isalnum())
print ('Ele tem dígitos?', n1.isdigit())
print ('Ele está em letras minúsculas?', n1.islower())
print ('Ele está em letras maiúsculas?', n1.isupper())
print ('Ele é capitalizado?', n1.istitle())
